name: main
on: [push]
jobs:
  build:
    name: Build on ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: x86
          - os: ubuntu-20.04
            arch: x86
            pg_version: 13
          - os: ubuntu-20.04
            arch: x86
            pg_version: 12
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive

      - if: matrix.os == 'macos-latest'
        run: brew install libpq postgresql

      - if: matrix.os == 'ubuntu-20.04' && matrix.pg_version == '13'
        run: sudo apt install libpq-dev postgresql postgresql-contrib postgresql-server-dev-13

      - if: matrix.os == 'ubuntu-20.04' && matrix.pg_version == '12'
        run: sudo apt remove postgresql libpq-dev libpq5
      - if: matrix.os == 'ubuntu-20.04' && matrix.pg_version == '12'
        run: sudo apt install libpq5=12.6-0ubuntu0.20.04.1 libpq-dev=12.6-0ubuntu0.20.04.1 postgresql=12+214ubuntu0.1 postgresql-contrib=12+214ubuntu0.1 postgresql-server-dev-12

      - run: make
      - run: ls -l
      - run: git status
      - run: file fzy.so
      - run: make stash_precompiled_binary
      - run: rm -f *.o
      - run: rm -f *.bc
      - uses: romgrk/publish-to-github@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
